
(defpackage :clws.connection
  (:use :cl)
  (:export :websocketconnection)
  (:export :start-connection)
  (:export :close-connection)
  (:export :connection-http-request)
  (:export :connection-handler)
  (:export :read-frame)
  (:export :policy-violation-error))

(defpackage :clws.frame
  (:use :cl)
  (:export :protocol-error)
  (:export :inconsistent-data-error)
  (:export :read-frame)
  (:export :write-frame)
  (:export :fin-frame-p)
  (:export :get-rsv)
  (:export :get-opcode)
  (:export :get-payload-length)
  (:export :get-mask)
  (:export :get-payload)
  (:export :continuation-frame-p)
  (:export :text-frame-p)
  (:export :binary-frame-p)
  (:export :close-frame-p)
  (:export :ping-frame-p)
  (:export :pong-frame-p)
  (:export :valid-close-status-code-p)
  (:export :control-opcode-p)
  (:export :+OPCODE-TEXT+)
  (:export :+OPCODE-BINARY+)
  (:export :+OPCODE-CLOSE+)
  (:export :+OPCODE-PING+)
  (:export :+OPCODE-PONG+)
  (:export :+OPCODE-CONTINUATION+)
  (:export :parse-close-payload)
  (:export :make-close-payload)
  (:export :+STATUS-CODE-NORMAL-CLOSURE+)
  (:export :+STATUS-CODE-GOING-AWAY+)
  (:export :+STATUS-CODE-PROTOCOL-ERROR+)
  (:export :+STATUS-CODE-CANNOT-ACCEPT-DATA+)
  (:export :+STATUS-CODE-INCONSISTENT-DATA+)
  (:export :+STATUS-CODE-POLICY-VIOLATION+)
  (:export :+STATUS-CODE-DATA-TOO-BIG+)
  (:export :+STATUS-CODE-UNNEGOTIATED-EXTENSION+)
  (:export :+STATUS-CODE-UNEXPECTED-CONDITION+))

(defpackage :clws.binary-types
  (:use :cl)
  (:export :read-uint-64)
  (:export :read-uint-32)
  (:export :read-uint-16)
  (:export :read-uint-8)
  (:export :write-uint-64)
  (:export :write-uint-32)
  (:export :write-uint-16))

(defpackage :clws.handler
  (:use :cl)
  (:export :connection-handler)
  (:export :on-open-connection)
  (:export :on-close-connection)
  (:export :on-text-message)
  (:export :on-binary-message)
  (:export :close-connection)
  (:export :send-text-message)
  (:export :send-binary-message))
 
(defpackage :clws.socket
  (:use :cl)
  (:export :connection-socket)
  (:export :connection-socket-usocket)
  (:export :connection-socket-close)
  (:export :connection-socket-socket-stream))


